[package]
name = "copy_to_qr"
version = "0.1.0"
authors = ["Joseph Catrambone <jo.jcat@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.13.0" # Included for plain display.  
qrcode = { version = "0.8", default-features = false } # default-features include code.render.
clipboard = "0.5.0"
